### ISSUE TITLE
error on fb2k startup

### ISSUE THREAD

**Issue by ASopH** [tomato111/smp-scripts#2]
Hi, little crash on fb2k startup in smp-cover !

Error: Spider Monkey Panel v1.6.1 (smp-cover: smp-cover v1.1.1 by tomato111)
Clone failed:
Failed to create GdiPlus object (0x3): OutOfMemory

File: smp-cover.js
Line: 203, Column: 19
Stack trace:
  createReflImg@smp-cover.js:203:19
  ImageLoader</this.getImg@smp-cover.js:237:31
  Display</this.changeImage@smp-cover.js:367:36
  changeImg@smp-cover.js:486:26
  Controller</this.onNewTrack@smp-cover.js:546:13
  on_item_focus_change@smp-cover.js:817:41
  on_playback_stop@smp-cover.js:830:13
  @smp-cover.js:787:5
  Function.prototype.timeout/this.$$timeout_timerid$$<@lib.js:66:13

after reloading all seems ok.
It only happens, when fb2k is started - not on restart fb2k

cheers :-)

**Comment by ASopH** [comment]
me again,

edit: It only happens, when fb2k is started and it's not visible (i.e. non active Tab)

**Comment by tomato111** [comment]
Please try the new version(v1.4).

**Comment by ASopH** [comment]
Hi,
  works like a charm, thx
